#!/bin/bash
xset dpms 0 0 0
xset s off
xset s noblank
rm -rf ~/.config/chromium/Singleton*
exec chromium-browser /usr/share/unitotem-manager/templates/boot-screen.html \
	--remote-debugging-port=9222 \
	--incognito \
	--noerrdialogs \
	--disable-translate \
	--no-first-run \
	--fast \
	--fast-start \
	--disable-infobars \
	--disable-restore-session-state \
	--disable-features=TranslateUI \
	--enable-features=OverlayScrollbar \
	--disk-cache-dir=/dev/null \
	--ignore-certificate-errors \
	--kiosk \
	--start-fullscreen \
	--window-position=0,0 \
	--window-size=$(cat /sys/class/graphics/fb0/virtual_size)
